name: License Verification

on:
  pull_request:
    branches: '**'

jobs:
  verify-license:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Install Very Good CLI
        run: dart pub global activate very_good_cli
        
      - name: Verify License Headers
        run: very_good packages check licenses --dependency-type=transitive --allowed=MIT
        
      - name: Check License Compliance
        if: failure()
        run: |
          echo "::error::License verification failed. Please ensure all files have proper license headers."
          exit 1
