name: SBOM Generation and Vulnerability Scan

on:
  push:
    branches:
      - '**'  # Trigger on all branches
#   pull_request:
#     branches:
#       - '**'  # Trigger on all pull requests

jobs:
  sbom-and-vuln-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Syft
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      # Step 3: Generate SBOM with Syft
      - name: Generate SBOM
        run: |
          syft dir:. -o cyclonedx-json > sbom.json

      # Step 4: Upload SBOM as Artifact
      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.json

      # Step 5: Install Grype
      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      # Step 6: Perform Vulnerability Scan using Grype
      - name: Vulnerability Scan
        run: |
          grype sbom:sbom.json --fail-on low
